#!/usr/bin/with-contenv bash

# Set UID and GID
PUID=${PUID:-1001}
PGID=${PGID:-1001}

# Change UID and GID for user
usermod -o -u "$PUID" abc
groupmod -o -g "$PGID" abc

# Print UID and GIDec
echo -e "UID: $(id -u abc)\nGID: $(id -g abc)"