#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Set UID and GID
PUID=${PUID:-1001}
PGID=${PGID:-1001}

# Change UID and GID for user
usermod -o -u "$PUID" abc
groupmod -o -g "$PGID" abc

# Print UID and GID
echo -e "UID: $(id -u abc)\nGID: $(id -g abc)"

# Give abc user permisisons to the folders
chown -R abc:abc /app
chown -R abc:abc /default
chown -R abc:abc /config

echo "Made by MiguelNdeCarvalho"