name: Test Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint-bash:
    name: Lint Bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Bash (Shellcheck)
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './rootfs/etc/cont-init.d'
          additional_files: '01-userpermissions'
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v2.0.0